### ISSUE TITLE
Chambers reciphers already ciphered values (if they are long enough)

### ISSUE THREAD

**Issue by ace** [thekompanee/chamber#48] opened 2016-12-01 18:22 UTC
Running `chamber secure` several times results in some values being reciphered in every execution.
If the clear value has at most 119 characters, everything is ok and its ciphered value is not modified. But with a 120 characters string every execution ciphers the previous value.

**Comment by jfelchner** [comment] 2016-12-01 18:49
@ace thank you for reporting.  This is a known issue due to the fact that longer values need to use a different cipher style than shorter values.  The typical use case for this is to store a private RSA key as a value encrypted by your Chamber key.

I'll leave this open and I'll try to get to it soon.

**Comment by ace** [comment] 2016-12-01 21:17
Thanks for the info, @jfelchner. I'll keep an eye here.

**Comment by jfelchner** [comment] 2017-02-04 07:21
@ace this has been fixed in 2.10.0.  Thanks for the patience.

**Closed by jfelchner** 2017-02-04 07:21 UTC

**Comment by jfelchner** [comment] 2017-02-09 18:13
@ace there was still a small bug where calling `secure` would show that it was going to encrypt it again (even though it didn't actually do it).  This has been fixed in `2.10.1` along with a bug caused by more recent versions of Thor.

**Comment by ace** [comment] 2017-02-09 18:17
@jfelchner thanks for the info, and the fix.
